#spring.application.name=SpringAiDemo
#spring.ai.openai.api-key=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



spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

spring.ai.openai.image.enabled=false